#!/bin/bash
# ---------------------------------------------------------------------------
# GENERATED by vscode_job.sh -- re-run vscode_job.sh to change resources.
# Do not edit by hand; your changes will be overwritten.
# Used as the ProxyCommand target for VS Code Remote-SSH on Skipjack.
# ---------------------------------------------------------------------------
set -euo pipefail

# A non-interactive ssh (how VS Code calls this) does not load the Slurm PATH.
export PATH="/opt/mprov/cloack/slurm/current/bin:$PATH"

echo "vscode-jump: allocating job..." >&2

exec salloc --partition=interactive_gpu --qos=class --account=en535743-ext-mrafiei1 --nodes=1 --ntasks=1 --cpus-per-task=10 --mem=32000M --gres=gpu:2g.40gb:1 --time=04:00:00 --comment=accept_cost --job-name=vscode \
  /bin/bash -c '
    # Resolve the first allocated node (handles ranges like csr[048-050]).
    node="$(scontrol show hostnames "$SLURM_NODELIST" | head -1)"
    # Skipjack has no netcat, so we use the bash-native /dev/tcp to reach the
    # node sshd. On disconnect this exits and salloc releases the job.
    exec 3<>"/dev/tcp/${node}/22"
    cat <&3 &
    up=$!
    cat >&3
    kill "$up" 2>/dev/null || true
  '
